### ISSUE TITLE
(Unrelated?) Add contact author button.

### ISSUE THREAD

**Issue by CreativeMasterBonin** [leveleditor/CAMM-Crystal-Alien-Map-Maker#3]
Just in case for later things, could this be a new feature? Because if things like 503 errors on wikifoundry not working then that means we need a new contact button on CAMM for issue tracking and stuff like that. Could be a feature, and noticed it was missing from credits. This is an error with WIkifoundry in general. We need a more reliable source of contact.
<img width="1354" alt="screen shot 2018-08-08 at 10 48 53 am" src="https://user-images.githubusercontent.com/17255831/43844907-c492c876-9af8-11e8-9cb7-215425fb93df.png">

- [ Add new contact button ]

**Comment by leveleditor** [comment]
I don't think any new feature needs to be added for this.

You've just contacted me right here on GitHub, which is the preferred way to contact me when you have a question/issue/etc. about CAMM, and it is now linked under the "Help" menu as of the last update, **however** this GitHub is _only_ for CAMM and _not_ for the wiki.

As far as WikiFoundry goes, we need a more reliable wiki site in general, which we are working on separately.
Since the current error seems to be affecting wikifoundrycentral.com also, I'm sure it will be resolved "soon".

I will say that we do have an alternate place of contact right now, which is a Discord server that was created for the MMW community in general, however we haven't really sent out very many invites yet.
Feel free to join using this one-time invite link: https://discord.gg/nr7m8RT
