### ISSUE TITLE
CAMM Cannot Find CAC Player In "/Applications" Folder using 'Wine'

### ISSUE THREAD

**Issue by CreativeMasterBonin** [leveleditor/CAMM-Crystal-Alien-Map-Maker#4]
CAMM Cannot find the CAC Player in the "/Applications" folder when using 'Wine'.
Even if you have put the player in the right area.

The Following Screenshot shows where everything is currently:

[The Blue Boxes Hide personal apps and data]

<img width="404" alt="Screen Shot 2019-04-25 at 4 32 17 PM" src="https://user-images.githubusercontent.com/17255831/56766709-0b031a80-6778-11e9-8e3a-da4b576e36bb.png">

Is this a bug? Or did I do something wrong here that's not obvious.

**Comment by leveleditor** [comment]
The problem here is with Wine. When you use Wine, it pretends to be Windows, so CAMM would think "oh you are running Windows" and look for the Windows (not MacOS) version of CAC Player.

There is an emulated Windows "Program Files" folder in Wine, however, since you are on a Mac, you have installed the Mac version of CAC Player, and you can't install the Windows version of it into Wine.

You could try running CAMM with Mono instead of Wine, which should then detect it's running on MacOS and launch the CAC Player correctly from the MacOS location.

Whenever I get around to making a MacOS download for CAMM, it will use a bundled version of Mono runtime so that this will work properly.

Ultimately, I can't support running CAMM using Wine, so this issue with Wine will not be fixed.

**Comment by jamieleealter** [comment]
Hi! I'm here because apparently I subscribed to this thread years ago.
Yes, as you see wine is a great application but it isn't perfect.

You might also try a VM (virtual machine)
good luck!
