### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by Landlighter** [leveleditor/CAMM-Crystal-Alien-Map-Maker#6]
Noticed a few things that could improve the game; no bugs really, just things to consider:
-Music should have all the different tracks
-Unit positions in the editor should change (they do change in game but their visuals don’t change in the editor which can be confusing)
-Crates and collectibles should be able to contain units (resolved)
-Flavor text and screen jumps at the beginning of the level (start up the real game and go to conflict mode and you'll see what I mean)
-something I just remembered, at the top left of every map, a cycle of every unit in the game is playing and I was just wondering if that was to store the animations?

I don't know a lot about code so I don't know what of this is impossible, but, as I said, none of it is required
I love this game

**Comment by Brian151** [comment]
wasn't aware music selection was implemented? last i checked, it wasn't...
clarify?
the way CAC actually does this is a bit messy...
i believe that is planned

oh, none of it is impossible, just takes time...

**Comment by CreativeMasterBonin** [comment]
Note: To put units in crates you must click the Box at the bottom where you normally put money amounts. Figured this out by looking at other levels included with CAMM.

**Comment by Landlighter** [comment]
Ah, okay. I’ll have to try that, but I can’t because my family is on a trip. So I don’t actually have a computer for a month! I’m sending this from my iPad!🤪

**Comment by Landlighter** [comment]
I’m home now, but I can’t find the box that you were talking about?
So I’m still not sure how to operate the surprise mechanics

**Comment by Landlighter** [comment]
[Crystalien Map Maker Putting units into crates.docx](https://github.com/leveleditor/CAMM-Crystal-Alien-Map-Maker/files/3387865/Crystalien.Map.Maker.Putting.units.into.crates.docx)

**Comment by leveleditor** [comment]
Although this issue has been closed, I'd like to address some of the points here for reference.
I'll do the same for your newer issue (#9) as well.

> -Music should have all the different tracks

This is now being tracked as part of issue #13 (previously on todo list)

> -Unit positions in the editor should change (they do change in game but their visuals don’t change in the editor which can be confusing)

By this I suspect you mean the angle/direction the units are facing.
This will be part of issue #17 "Sprite rotations for angles" (previously on todo list)

> -Flavor text and screen jumps at the beginning of the level (start up the real game and go to conflict mode and you'll see what I mean)

This is part of the indicator/dialogue system in the game.
Adding support for editing this is now being tracked on issue #25 (previously on todo list)

> -something I just remembered, at the top left of every map, a cycle of every unit in the game is playing and I was just wondering if that was to store the animations?

That's actually a bug that was most likely caused when setting a negative number (fixed), or an otherwise incorrect value on the "Monolithic property of things". This field has been quite a pain as it's hard to understand and explain, so I'll be making an effort to improve it. The related details are now being tracked on issue #11 (previously on todo list)

> I don't know a lot about code so I don't know what of this is impossible, but, as I said, none of it is required
> I love this game

That's quite alright, no need to get into the coding details if you don't want to.

Something to just keep in mind when reporting issues or suggestions here on GitHub, it's best to stick to opening one issue per thing to help us keep things organized.

**Comment by Landlighter** [comment]
Thanks for being awesome! I closed this issue because I saw you open a bunch of stuff related to it, so it was no longer needed
